staticlib_make : add.o subtract.o multiply.o divide.o main.o
	gcc -o staticlib_make add.o subtract.o multiply.o divide.o main.o; ./staticlib_make

add.o : add.c
	gcc -c add.c

subtract.o : subtract.c
	gcc -c subtract.c

multiply.o : multiply.c
	gcc -c multiply.c

divide.o : divide.c
	gcc -c divide.c

main.o : main.c
	gcc -c main.c





