######################################################################
# Automatically generated by qmake (3.0) ? 12? 14 17:11:34 2021
######################################################################
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets
TEMPLATE = app
TARGET = Talk
INCLUDEPATH += .

# Input
QT+=uitools
RESOURCES = Talk.qrc
SOURCES += Talk.cpp 
